import type { VaultProject, VaultSnippet } from "@/lib/types";

const now = new Date("2026-06-04T12:00:00").toISOString();

export const fallbackProjects: VaultProject[] = [
  {
    id: "atlas-reserve",
    name: "Atlas Reserve",
    client: "Atlas",
    description: "Sistema de reservas com painel operacional e controle de disponibilidade.",
    status: "Em produção",
    stack: "Next.js, TypeScript, Prisma, Tailwind",
    githubUrl: "https://github.com/",
    deployUrl: "https://atlasreserve.vercel.app/",
    notes: "Projeto: https://atlasreserve.vercel.app/",
    favorite: true,
    projectValue: 2500,
    maintenanceActive: true,
    maintenanceValue: 250,
    paymentStatus: "Pago",
    nextPaymentDate: "2026-07-10T12:00:00.000Z",
    projectType: "Dashboard",
    lastUpdate: "2026-06-13T12:00:00.000Z",
    problemsSolved: "realtime reservas, controle de disponibilidade, dashboard admin",
    promptUsed: "Prompt Codex para dashboard operacional de reservas.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "arena-chapas",
    name: "Arena Chapas",
    client: "Arena Chapas",
    description: "Organizador de pedidos e acompanhamento de produção.",
    status: "Em andamento",
    stack: "Next.js, SQLite, shadcn/ui",
    githubUrl: "https://github.com/hitalocods/ArenaChapas",
    deployUrl: "https://arenachapas-de41d.web.app/#",
    notes: "Valor 1000, sem mensalidade no momento.",
    favorite: false,
    projectValue: 1200,
    maintenanceActive: true,
    maintenanceValue: 120,
    paymentStatus: "Pendente",
    nextPaymentDate: "2026-07-15T12:00:00.000Z",
    projectType: "App",
    lastUpdate: "2026-06-12T12:00:00.000Z",
    problemsSolved: "fluxo pedidos, produção, consulta rápida",
    promptUsed: "Prompt dashboard simples para organizar pedidos.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "atlas-estoque",
    name: "Atlas Estoque",
    client: "Atlas",
    description: "Controle leve de estoque para produtos, movimentações e alertas.",
    status: "Em andamento",
    stack: "Next.js, Prisma, SQLite, Lucide",
    githubUrl: "https://github.com/hitalocods/AtlasEstoque",
    deployUrl: "https://atlas-estoque.vercel.app/",
    notes: "Status comercial: em negociação.",
    favorite: true,
    projectValue: 1800,
    maintenanceActive: true,
    maintenanceValue: 180,
    paymentStatus: "Atrasado",
    nextPaymentDate: "2026-07-05T12:00:00.000Z",
    projectType: "Dashboard",
    lastUpdate: "2026-06-10T12:00:00.000Z",
    problemsSolved: "crud estoque, alertas, relatórios",
    promptUsed: "Prompt dashboard de estoque com CRUD direto.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "cibele",
    name: "Cibele",
    client: "CS Studio Beauty",
    description: "Sistema de agendamento para studio de beleza.",
    status: "Em produção",
    stack: "React, Firebase, CSS",
    githubUrl: "https://github.com/hitalocods/Agendamento",
    deployUrl: "https://cs-studiobeauty.web.app/",
    notes: "Vendido por 200 sem mensalidade.",
    favorite: false,
    projectValue: 200,
    maintenanceActive: false,
    maintenanceValue: 0,
    paymentStatus: "Pago",
    nextPaymentDate: null,
    projectType: "App",
    lastUpdate: "2026-06-04T12:00:00.000Z",
    problemsSolved: "auth, agendamento, Firebase deploy",
    promptUsed: "Prompt app de agendamento simples.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "eventos-the",
    name: "Eventos THE",
    client: "THE",
    description: "Base para projetos de eventos, páginas públicas e controle interno.",
    status: "Concluído",
    stack: "Next.js, TypeScript, Vercel",
    githubUrl: "https://github.com/",
    deployUrl: "https://eventos-the.web.app/",
    notes: "Observação: em andamento.",
    favorite: true,
    projectValue: 900,
    maintenanceActive: false,
    maintenanceValue: 0,
    paymentStatus: "Cancelado",
    nextPaymentDate: null,
    projectType: "Landing",
    lastUpdate: "2026-06-07T12:00:00.000Z",
    problemsSolved: "landing eventos, publicação, checklist deploy",
    promptUsed: "Prompt landing de eventos.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "larissa",
    name: "Larissa",
    client: "Larissa Santana",
    description: "Projeto web para apresentação profissional.",
    status: "Em produção",
    stack: "Next.js, TypeScript, Vercel",
    githubUrl: "https://github.com/hitalocods/LarissaSantana",
    deployUrl: "https://larissa-santana.vercel.app/",
    notes: "Valor registrado: 200 reais.",
    favorite: false,
    projectValue: 200,
    maintenanceActive: false,
    maintenanceValue: 0,
    paymentStatus: "Pago",
    nextPaymentDate: null,
    projectType: "Landing",
    lastUpdate: "2026-06-02T12:00:00.000Z",
    problemsSolved: "copy, deploy Vercel, responsividade",
    promptUsed: "Prompt landing profissional.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "rimpots",
    name: "Rimpots",
    client: "RR Acessórios",
    description: "Projeto web para RR Acessórios com deploy e repositório organizados no vault.",
    status: "Em produção",
    stack: "Next.js, TypeScript, Vercel",
    githubUrl: "https://github.com/hitalocods/RRAcessorios",
    deployUrl: "https://rr-acessorios.vercel.app/",
    notes: "GitHub e deploy salvos.",
    favorite: false,
    projectValue: 650,
    maintenanceActive: true,
    maintenanceValue: 90,
    paymentStatus: "Pendente",
    nextPaymentDate: "2026-07-20T12:00:00.000Z",
    projectType: "Site",
    lastUpdate: "2026-06-08T12:00:00.000Z",
    problemsSolved: "catálogo, deploy Vercel, imagens",
    promptUsed: "Prompt site comercial leve.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
  {
    id: "trino",
    name: "Trino",
    client: "Trino",
    description: "Dashboard minimalista para centralizar links, deploys e notas técnicas.",
    status: "Ideia",
    stack: "React, Tailwind, Framer Motion",
    githubUrl: "https://github.com/hitalocods/trinoimobiliaria",
    deployUrl: "https://trino-imobiliaria.web.app/",
    notes: "Negociando a mensalidade. Vendido por 1000.",
    favorite: false,
    projectValue: 1000,
    maintenanceActive: false,
    maintenanceValue: 0,
    paymentStatus: "Pago",
    nextPaymentDate: null,
    projectType: "Site",
    lastUpdate: "2026-06-14T12:00:00.000Z",
    problemsSolved: "landing imobiliária, deploy Firebase, organização de proposta",
    promptUsed: "Prompt landing imobiliária.",
    createdAt: now,
    updatedAt: now,
    timeline: [],
  },
];

export const fallbackSnippets: VaultSnippet[] = [
  {
    id: "prompt-dashboard-premium",
    title: "Prompt dashboard premium",
    content: "Crie um dashboard premium, escuro, denso e operacional para um OS de freelancer com cards, filtros, modais e métricas reais.",
    category: "Prompt",
    tag: "codex, ui, dashboard",
    favorite: true,
    createdAt: now,
  },
  {
    id: "next-dev",
    title: "Next dev",
    content: "npm run dev",
    category: "Deploy",
    tag: "next, local",
    favorite: false,
    createdAt: now,
  },
];
